#-------------------------------
# General Site Settings

menu:
- {name: '', url: ''}
- {name: 'SHOP', url: 'https://shop.kutalp.com'}
- {name: 'Blog', url: 'https://kutalp.com/pages/blog.html'}
- {name: 'Contact', url: 'https://kutalp.com/pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'KUTALP|Self-employed Designer/Maker. Shop on etsy.com'
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-153515484-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # KUTALP DOGAN

  I am a self-employed Designer/Maker. I am deeply passionate about my Workshop, developing my Skillset and Making Stuff.

contact: >
  # Contact

  You may contact me [through my email](mailto:support@kutalp.com)

#-------------------------------
# Work Section

projects:
- {name: 'Embroidery Patches', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Leather Craft', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Oil Painting', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Ceramic Tile Craft', folder: 'proj-4', file: 'projects/proj-4.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'https://twitter.com/KutalpD'}
- {icon: 'instagram', link: 'https://instagram.com/kutalpd/'}
- {icon: 'facebook', link: 'https://fb.me/KutalpShop'}
- {icon: 'envelope', link: 'mailto:support@kutalp.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
